# Generated by Django 4.2.3 on 2023-09-16 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_certificate_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="github",
            field=models.URLField(
                validators=[django.core.validators.URLValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkedin",
            field=models.URLField(
                validators=[django.core.validators.URLValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MaxLengthValidator(limit_value=100)
                ],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="github_url",
            field=models.URLField(
                validators=[django.core.validators.URLValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="key_skill",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MaxLengthValidator(limit_value=50)
                ],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="keyword",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MaxLengthValidator(limit_value=50)
                ],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MaxLengthValidator(limit_value=50)
                ],
            ),
        ),
    ]
