# Generated by Django 4.2.3 on 2023-09-23 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0006_alter_profile_github_alter_profile_linkedin_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="certifying_institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="projects.certifyinginstitution",
            ),
        ),
    ]
